### ISSUE TITLE
tweakpane

### ISSUE THREAD

**Issue by xaliphostes** [youwol/cdn-externals#4]
### Registry

npmjs.com

### Package name

tweakpane

### Package version

latest

### Package license

MIT

### Checklist

- [X] requested version of the npm package not already in Youwol CDN (use [cdn-explorer](https://platform.youwol.com/applications/@youwol/cdn-explorer/latest))
- [X] npm package exists in the npm registry specified with the name, version and license specified

### Other informations

Hello world :-)

**Comment by youwol-guillaume** [comment]
done
